name: Common python github action setup

description: >
  Common infrastructure setup which checks out code, sets up python and pipenv,
  and assumes an AWS role with OIDC integration. This requires that OIDC integration 
  with an IAM role is setup so that the github repo can assume the role to deploy 
  to your AWS account.

author: Tess Thyer

inputs:

  python_version:
    description: version of python to use
    required: false
    default: "3.10"

  aws_region:
    description: name of AWS region
    required: false
    default: "us-east-1"

  role_to_assume:
    description: iam role assumed for deployments
    required: true

  role_session_name:
    description: name for iam role session
    required: false
    default: "GitHubActions"

  role_duration_seconds:
    description: >
      credentials session duration when assuming role
    required: false
    default: 1200

runs:

  using: composite

  steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install pipenv
        shell: bash
        run: python -m pip install pipenv

      - name: Install dependencies
        env:
          PIPENV_NOSPIN: 'true'
        shell: bash
        run: |
          pipenv install --dev

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ inputs.role_to_assume }}
          role-session-name: ${{ inputs.role_session_name }}
          role-duration-seconds: ${{ inputs.role_duration_seconds }}
